FROM php:8-apache

WORKDIR /var/www/html

# PHP で必要なライブラリをインストール
RUN apt-get update \
    && apt-get install -y libonig-dev libzip-dev unzip mariadb-client \
    && docker-php-ext-install mbstring zip bcmath pdo_mysql mysqli \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug
# タイムゾーン設定
ENV TZ=Asia/Tokyo

# mod_rewrite モジュールを使えるようにする
RUN a2enmod rewrite

# アプリケーションフォルダを環境変数として設定
ENV APP_HOME /var/www/html

# ソースコードと.envファイルをDockerImageに埋め込む
COPY . $APP_HOME

COPY .htaccess /var/www/html/.htaccess

# composer のインストール
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

