name: Test

on:
  push:
    branches:
      - master
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: docker-compose up
      run: |
      # docker-compose build
      docker-compose up -d
    - name: composer install
      run: |
        docker-compose exec app composer install
    - name: phpunit
      runs: |
        docker-compose exec app ./vendor/bin/phpunit tests
        


